name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      run: 
        xcodebuild -alltargets -configuration Release | xcpretty && exit ${PIPESTATUS[0]}
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/Release
        if-no-files-found: error
