name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - run: xcodebuild -configuration=Release
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/Release
      - name: Upload build
        uses: svenstaro/upload-release-action@2.9.0
        if: github.event_name != 'pull_request'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_output.zip
          tag: refs/heads/master
          release_name: RTL8111_driver_for_OS_X
          body: Update objective-c-xcode.yml
          file_glob: false
          overwrite: true
